import json
import spacy
from collections import Counter, defaultdict
from pprint import pprint


nlp = spacy.load("tr_core_news_trf")

all_yorumlar = [json.loads(line) for line in open("../corona_yorumlari-processed.jsonl", "r").read().split("\n")[:-1]]


adjs=[]
nouns=[]
verbs=[]

i=0


counter = Counter({'c ve d vitamini': 4,
         'hiç bir belirti': 3,
         'tat ve koku kaybım': 3,
         'hafif baş ağrısı': 3,
         'en kısa zamanda': 2,
         'kalıcı bir hasar': 2,
         'sadece burun akıntısı': 2,
         'hafif burun akıntısı': 2,
         '%50 oranında': 2,
         'bir tane parol': 2,
         'ilçe sağlık müdürlüğünden': 2,
         'herhangi bir etkisi': 2,
         'bir iki gün': 2,
         'tat ve koku kaybının': 2,
         'belde hafif ağrı': 2,
         '3 er tane': 2,
         'rahatsız edici düzeyde': 2,
         'ilacın son dozunu': 2,
         'bir önceki gün': 2,
         'on birinci gün': 2,
         'koku ve tat duyum': 2,
         'hiç bir belirtim': 2,
         'deliksiz bir uyku': 2,
         'geniz akıntısı devam': 2,
         'daha ciddi vakalarda': 1,
         'enfeksiyonun yaygın belirtileri': 1,
         'ileri yaştaki bireyler': 1,
         'yılın 12 ayı': 1,
         've alerji semptomlarını': 1,
         'bu hastalığın semptomlarının sırası': 1,
         'hiç bir belirtiyi': 1,
         'gribin bazı belirtileri': 1,
         'eklem ve vücut ağrısı': 1,
         'öncelikle bu bir grip': 1,
         'toplam 1 ay': 1,
         'okuduklarımdan gördüğüm o': 1,
         'burun akıntısı öksürük': 1,
         'anladığım kadarıyla olmayan sıradır': 1,
         'salgının belirtileri hakkında': 1,
         'olası belirtilerin facebook grupları': 1,
         'çok büyük yol': 1,
         'sıradan bir üşütme': 1,
         'sadece boğaz ağrım': 1,
         'daha düşük vücut sıcaklıkları': 1,
         'bakteriyel pnömonilerin aksine': 1,
         'mavi bir renge': 1,
         'diğer tüm semptomlarınızı': 1,
         'telefondaki sağlık personeline': 1,
         '112 acil yardım hattını': 1,
         'acil durum semptomları': 1,
         'kaburgalarda ezilme hissiyatı': 1,
         'uzman dr tarafından': 1,
         'şöyle bir video': 1,
         'kuluçka süresince hiçbirisidir': 1,
         'bir topak balgam': 1,
         'akciğerlerinizin alt kısımlarında': 1,
         'basit bir biçimde': 1,
         'akciğerlerde doluluk hissidir': 1,
         'oradan organ yetmezliği': 1,
         'virüsün tek bir amacı': 1,
         'madem belirtileri ateş': 1,
         'gün gün yaşadığı semptomları': 1,
         'bugun göçmenlerin durumunu': 1,
         'hastanede yatan arkadaşımın': 1,
         'peşine başlayan öksürük': 1,
         'hafif boğaz ağrısı': 1,
         'son üç belirtiden biri': 1,
         'hemen kendinizi izole': 1,
         'hiç başka bir ihtimal': 1,
         '- şiddetli halsizlik': 1,
         'sürekli yaşadığım bir olay': 1,
         'kaşıntılı bir döküntüye': 1,
         'yeni bir belirtisinin': 1,
         'yer alan habere': 1,
         'bu koronavirüse işaret': 1,
         'kaşıntılı bir döküntü': 1,
         'hastalığa yakalananlar tarafından': 1,
         'boğazda gıcık hissi': 1,
         '3 ay sonraya': 1,
         'yapılması gereken şey': 1,
         'bunun covid-19 olduğuna yemin': 1,
         'en belirgin bunlardir': 1,
         'günlerce süren ates': 1,
         'okadar çok insanla temas': 1,
         'şuan yatakta durduk yere': 1,
         'aşağıda görülen belirtilerdir': 1,
         '-4 saati aşan ereksiyon': 1,
         'cumartesi sabahı editi': 1,
         'salgının ilk ayında': 1,
         'bu belirtilerin birebirini': 1,
         'hafiften baş ağrısı': 1,
         'mesaj atan herkese teşekkürler': 1,
         'ana belirtilerin hiçbiri': 1,
         'inceden bi boğaz ağrısı': 1,
         'buz gibi su': 1,
         'en yakın kuruluşa': 1,
         '2 kat maske tak': 1,
         'hafif bir halsizlik': 1,
         'böyle bir ağrı': 1,
         'en son belime': 1,
         'hafif göğüs ağrısı': 1,
         'solgun sarı renkleri': 1,
         'covid hasta rengi': 1,
         "''bir gözlem": 1,
         'nezle ve grip belirtilerine': 1,
         'yeni bir rapor': 1,
         've şu an': 1,
         'günü iş başıyım': 1,
         'cuma iş başı': 1,
         'yeniden bi test': 1,
         'ek bir sıkıntı': 1,
         'pozitif bi şeklilde': 1,
         'bir daha test': 1,
         '1 hafta daha rapor': 1,
         'hastane iş yeri hekimliğini': 1,
         'negatif çıkması halinde': 1,
         '19.11.20 12.00 tat koku': 1,
         've en ufak egzersizde': 1,
         'herhangi bir ateş': 1,
         'c d vitaminleri': 1,
         'saat 13.45 itibariyle': 1,
         '10 günlük rapor': 1,
         'favira adlı ilaç': 1,
         '9 bucuk itibariyle': 1,
         '38.6 civarlarında dolanan ateş': 1,
         'evdeki karantina sürecinde': 1,
         'ne olursa olsun karantinadayım': 1,
         'daha bu özellikler': 1,
         '20 kasimda baslayan belirtilere': 1,
         'bas agrisinin sebebi': 1,
         'tat ve koku kaybi': 1,
         'eklemlerim ince ince sizliyo': 1,
         '37.6 ates bas agrisi': 1,
         'dört gibi ilçe sağlıktan': 1,
         'bu sabahta test': 1,
         'aynı gün burun akıntısı': 1,
         'eklem ve kas ağrılarım': 1,
         'belirtileri hissettiğim ilk gün': 1,
         'başka bir şikayet': 1,
         'en son karantina': 1,
         'benle benzer süreç yaşayanlarda': 1,
         'bir aydan uzun zaman': 1,
         'bir uyku düzeni karmaşası': 1,
         'bu odaklanma sorunu': 1,
         'zihnimdeki kara bulutlar': 1,
         'neredeyse bir ay': 1,
         ', yani 20. gün': 1,
         'üst solunum yolu enfeksiyonu': 1,
         '20. gün test': 1,
         'tat ve koku hissini': 1,
         'bu aşamada doktordan randevu': 1,
         'bu solunum güçlüğü': 1,
         'belirtilerin başladığı tarihten': 1,
         'ilk ortaya çıkan belirtiler': 1,
         '38 derece civarı': 1,
         '4 aylık kızımıza': 1,
         '(3 kilo': 1,
         'çay demlenen evden': 1,
         'hiç bir şekilde': 1,
         'şiddetli baş ağrısı': 1,
         'normalden daha uzun surede': 1,
         '2 gun arayla': 1,
         'baska hic bir sikayetim': 1,
         'sac diplerimde agri': 1,
         'onun için ilaç yazsaydınız': 1,
         'boğaz ağrısı şikayeti': 1,
         'merak ettiğim bir şey': 1,
         'devlet hastanesi aciline': 1,
         'ince bir ceket': 1,
         'o ilk hafif belirtileri': 1,
         'benim sağ gözüm': 1,
         'ilk iki gün': 1,
         'tirt bir olayı': 1,
         'nefes darlığı sıralamasında': 1,
         'kas eklem ağrısı': 1,
         'yukarıda saydıklarımın hepsini': 1,
         'adlı lanet virüs': 1,
         'sürekli uyuma isteği': 1,
         'annem babam aşı': 1,
         'grip benzeri durumlar': 1,
         'zaten yılların etkisiyle': 1,
         'konuşmasını engelleyecek düzeyde': 1,
         'göz ve kulak ağrısı': 1,
         'sırt ve bacak ağrıları': 1,
         'covidim ingiliz varyantı': 1,
         'karantinanın 8. günündeyim': 1,
         'bir buçuk yıl': 1,
         'ölümcül kobra koviti': 1,
         'o kadar korku': 1,
         'şehirdışına gitme planım': 1,
         'özellikle bu dönem': 1,
         'limonlu tavuk çorbası': 1,
         'kemik suyu çorbası': 1,
         'd vitamni takviyesi': 1,
         ', naçizane magnezyum': 1,
         'sözlükte yazılan belirtileri': 1,
         'sirt ve bacak agrisi': 1,
         'tylol hot ismi': 1,
         'öyle bir şey': 1,
         'aşısız ufak oğlum': 1,
         'bugün - 5. gün': 1,
         'evde aşılı olan oğlum': 1,
         'tat alma duyum': 1,
         'hiç bir şeyim': 1,
         'ayın 12 si akşamı': 1,
         '2. doz üzerinden': 1,
         '2 doz biontech aşılıyım': 1,
         'beni sarsmayan belirtilerdir': 1,
         'aşırı baş ağrısı': 1,
         'kan sulandıcı etki': 1,
         'd vitamini takviyesini': 1,
         'ilk üç sonrasında': 1,
         'bazen 2 pıs': 1,
         '04 aralık cmt': 1,
         '03 aralık cuma': 1,
         '02 aralık perş': 1,
         'çocuğumun risk durumu': 1,
         '01 aralık çarş': 1,
         'bu burun akıntısından': 1,
         '30 kasım salı': 1,
         'çok yoğun mukus oluşumu': 1,
         'ekstra hiç bir sprey': 1,
         'hatrı sayılır bir sızı': 1,
         'resmi olarak 6. günüm': 1,
         'bir mukus üretimi': 1,
         'panik bir durum': 1,
         'yoğun kıvamlı mukus': 1,
         'kuvvetli bir burun tıkanıklığı': 1,
         'gözden başlayan ağrı': 1,
         've yine hafif ateş': 1,
         'bir gariplik hissiyatı': 1,
         'bende akşamüzeri hafif ateş': 1,
         've son ateşli gecesi': 1,
         '(yaklaşık 6 saat': 1,
         'pozitif vaka olduğu bilgisi': 1,
         'yoğun sırt ağrısı': 1,
         'soğuk algınlığı belirtileri': 1,
         'koku ve tat duyularım': 1,
         'kovid için test': 1,
         'bir anormallik olduğunu işaret': 1,
         'üşüme benzeri bir his': 1,
         'bu ilk gariplikti': 1,
         'kısa süreli boğaz ağrısı': 1,
         'yedi yaşındaki kızımın': 1,
         'uyudukça uyumak isteği': 1,
         '3 doz biontech aşılıyım': 1,
         'bacaklarımın ağrısından yürüyemeyecek duruma': 1,
         'bedensel sağlığım açısından': 1,
         'koku egzersizi yapın': 1,
         'tam aynı şekilde': 1,
         'nasıl bir sonuçla': 1,
         'şöyle bir test': 1,
         'gerçekte vücutta olanlardan': 1,
         'çok irrasyonel bir yaratık': 1,
         'kesin bir kural': 1,
         'omicron varyantı geçiren hastalar': 1,
         'çok büyük ihtimalle': 1,
         'çok ciddi farklara sebep': 1,
         'dolayısıyla bulguların ciddiyetine': 1,
         'virüsün vücuda girişinden': 1,
         'ciddi oranda mutasyon': 1,
         'iki yıllık pandemi süresince': 1,
         'çok ciddi farklar': 1,
         'akıntısı hariç sıkıntı': 1,
         'hepinize sağlıklı günler': 1,
         '15-20 entry': 1,
         'birkaç farklı başlıkta': 1,
         'tedavi süreçlerini nasıl geçirdikleriyle': 1,
         'bu kadar yüksek sayılar': 1,
         'aralık 2020 itibariyle': 1,
         'semptomlar birer işaret': 1,
         'bunun bizdeki karşılığı': 1,
         'anormal bir üremeye': 1,
         'herhangi bir ağrı': 1,
         'bir enerji düşüklüğü': 1,
         'hafif atlatacak kişilerde': 1,
         'önemli şey ise semptom': 1,
         'aile üyelerimden birisinin': 1,
         'ikincisi ise semptom': 1,
         'birincisi temas durumu': 1,
         'semptomların farklılık gösterebileceği akıldan': 1,
         'protein zengini gıdalar': 1,
         'yoğun sıvı tüketimi': 1,
         'ilk yaptığım şeyler': 1,
         'peki tedavi süreci': 1,
         'test yaptırma gereği': 1,
         '%70 seviyesine': 1,
         'herhangi bir semptom': 1,
         'kokusunu aldığım ilk şey': 1,
         'koku ve tat duyularımı': 1,
         'aynı günün akşamı': 1,
         'koku ve tat duyularında': 1,
         'nadir gelen burun akıntısı': 1,
         'dayanılmaz bir ağrı': 1,
         'genel olarak eklem bölgelerimde': 1,
         'benim covid sürecim': 1,
         'başka bir entryde': 1,
         'bir kalp enzimim': 1,
         'geçmeyen kemik ağrıları': 1,
         'hafif de ateş': 1,
         'yabancı bir organizmayla': 1,
         'o halsizliği yaşayan vücudum': 1,
         'başımı koyacak yastık': 1,
         'öyle bir halsizlik': 1,
         'çok hafif iştahsızlık': 1,
         'ilk 3 gün': 1,
         'tuvalet vs. gibi alanlarda': 1,
         'var olan hastalıklarını': 1,
         'içilen ilaç sayısı': 1,
         '2 adet ilaç': 1,
         'damla d vitamini': 1,
         'neredeyse 1 ay': 1,
         'ciddi bir sorun': 1,
         'ilaçları kullanmak önemli': 1,
         '3 gün sonraya': 1,
         'sinüslerimin dolması sonucu': 1,
         'sadece biraz şakaklarda ağrı': 1,
         '2-3 saat': 1,
         'bir ağrı kesici': 1,
         'buna ilaç mı sebep': 1,
         'bir tane aferin': 1,
         'biraz sırt ağrısı': 1,
         'ek bir takviye': 1,
         'ekstra verilen ilaçları': 1,
         'tüm hastalara şifa': 1,
         'ufak bir şüphe': 1,
         'yüzde 95 şans eseri': 1,
         'babamda aralıklı ateş': 1,
         'c, d vitamini': 1,
         'çoktan bulaşmış olma ihtimali': 1,
         'sıtma ilacı konusunda': 1,
         'favircovir ve sıtma ilacından': 1,
         'parol ve vitamin takviyesi': 1,
         'teşhisin 1. günü': 1,
         'bu başlığı bilmemem sebebiyle': 1,
         'hekim sirtimi olctu': 1,
         'az burun tikanikligi bar': 1,
         'feci burun tikanikligi': 1,
         'bademcigin şişlige devami': 1,
         '10 günlük macera': 1,
         'en önemli olan bu': 1,
         'çok ciddi belirtilerim': 1,
         'yine mide keyifsizligi devam': 1,
         'rahat bir gece': 1,
         'pek bir şey': 1,
         '2 tane parol': 1,
         'sonra 3lü ilaca devam': 1,
         'bırak bir yere': 1,
         'aynı sırt ağrısı': 1,
         'inanılmaz bir sırt ağrısı': 1,
         'olumsuz bir etkisi': 1,
         'ilk 8 favicoviri': 1,
         'bir buçuk saat': 1,
         'çok şiddetli olmayan öksürük': 1,
         '37-37.3 6.gün': 1,
         'bir paket ilaç': 1,
         'ne biçim bir grip': 1,
         '5.gün burun tıkanıklığı yorgunluk': 1,
         '4.gün hafif öksürük': 1,
         'hafif bir ateş': 1,
         '3.gün hafif öksürük': 1,
         'hafife alınacak bir şey': 1,
         'onun manevi yükü': 1,
         'ilk 8 gün': 1,
         'beslenmeme de özen': 1,
         'dil altı d vitamini': 1,
         'dün yapılan testleri': 1,
         'en büyük mutluluğum': 1,
         '- 9. gün': 1,
         'aşırı uyku hali': 1,
         'nefes alıp vermek yerine': 1,
         '- 6. gün': 1,
         'en ufak hareketimde': 1,
         'nezle gibi bir şey': 1,
         '- 5. gün': 1,
         '- 4. gün': 1,
         'herhangi bir ağrım': 1,
         '- 3. gün': 1,
         'işim bitince dokunduğum yerleri': 1,
         'boğazımda yanma devam': 1,
         'herhangi bir yan etkisi': 1,
         '- 2. gün': 1,
         'bel ve baş ağrısı': 1,
         'gece yarısı çıkan sonucum': 1,
         'en yakın hastaneye': 1,
         'bel ve baş ağrım': 1,
         'o akşamın sabahına': 1,
         '- 1. gün': 1,
         'benim de boğazımda': 1,
         'tipik covid belirtileriydi': 1,
         '24 gündür hafif ateş': 1,
         'hafif bir bogaz agrisi': 1,
         'ya da harbiden': 1,
         'bir hafta gibi sürede': 1,
         'ilk 7 gün': 1,
         'tekrar yazmamak adına': 1,
         'covid 19 belirtilerinin': 1,
         'şiddetli bir omuz ağrısı': 1,
         'en yakın arkadaşlarım': 1,
         'herhangi bir yere': 1,
         'ben ansiyete hastasıyım': 1,
         'tez zamanda şifalar': 1,
         'hagif göğüs ağrısı': 1,
         'hafif vucud ağrısı': 1,
         'akıntısı halsizlik devam': 1,
         'sonrası böbreklere özgürlük': 1,
         '3 hap şeklinde': 1,
         'alfa lipoik asit': 1,
         'ikinci 8 hapımı': 1,
         'kafam sepet gibi dediklerinden': 1,
         'öyle bir doluluk': 1,
         'öyle bir ağrı': 1,
         "8 tane favimol'u": 1,
         'emekleri için teşekkür': 1,
         'boğazımda tahriş olmuş hissiyatı': 1,
         'çalıştığım kurumdan 3 kişi': 1,
         'yorgunluk ve huzursuzluk hali': 1,
         'semptomlarımın başlangıç tarihini': 1,
         'geri kalan zamanda': 1,
         'kan sulandırıcı iğneler': 1,
         'internetten her gördüğünüze': 1,
         'başlaması gereken zamandan': 1,
         'aşırı derecede fazla su': 1,
         'bir tatlı kaşığı': 1,
         'biraz uzun konuştuğumda': 1,
         'hafif bel ağrısı': 1,
         'şiddetlenen boğaz ağrısı': 1,
         'yeni bir belirtiye': 1,
         'bizim gibi hafif semptomlarla': 1,
         'testi pozitif çıkanlarda': 1,
         'ilik suyu takviyesi': 1,
         'iki dilim limon': 1,
         'içme suyu şişeleri': 1,
         'karantina sürecinde verilen ilaçlarımızı': 1,
         'daha sonraki günde': 1,
         'benim koku kaybım': 1,
         'saat 11 civarı': 1,
         '25 kasım günü': 1,
         'dusuk iq’lu genleriniz': 1,
         '13-14 gün': 1,
         'yaklaşık 1 ay': 1,
         'bundan sonrası gözlem': 1,
         'ama hala tat': 1,
         'hiç baş ağrım': 1,
         '1 tane aspirini': 1,
         '2. doz 8 hapı': 1,
         'kan sulandırıcı aspirin': 1,
         'ilk 8 dozumu': 1,
         'sağlık bakanlığı tarafından': 1,
         'kalp atış hızı': 1,
         'hafif eklem ağrıları': 1,
         ', parol işe': 1,
         'boğazımda da gıcıklanma söz': 1,
         'hafif bir öksürük': 1,
         'tat ve koku kayıplarım': 1,
         'siyah kuru üzüm': 1,
         'bugün dokuzuncu günüm': 1,
         'bu büyük rahatlık': 1,
         't bölgesi ağrım': 1,
         'tam belirtilerim neydi': 1,
         '5 aralık günü': 1,
         'sürekli uyku hali': 1,
         'başta hastaneye gitmeye ayak': 1,
         '(6 aralık pazar': 1,
         'uzun vadeli bir etkisi': 1,
         'hafif hafif koku': 1,
         'dünden çok farkı': 1,
         'sağlam bir balgam': 1,
         'boğazda gıcıklama devam': 1,
         'bu sefer de ishal': 1,
         'kas ağrıları devam': 1,
         'baş ve kas ağrıları': 1,
         'farklı bir virüsle': 1,
         'çok az öksürük': 1,
         'pek de önemli': 1,
         'öğleden sonra biraz ateş': 1,
         'başkada bir şey': 1,
         'bilgisayarı hiç açmamaya karar': 1,
         'hafif bir şişlik': 1,
         'ilacı söylendiği şekilde': 1,
         '100% enerjim': 1,
         '%90 civarında': 1,
         'koca bir soğandan': 1,
         '10 günlük karantina sürem': 1,
         'test olduğum bu gün': 1,
         'hafif soğuk algınlığı': 1,
         'korona diye bir şey': 1,
         'gecenin 2 sine': 1,
         '1 adet minosette': 1,
         '1. gün akşamı': 1,
         'biraz beni kendime': 1,
         '1 tane minosette': 1,
         'sadece sınırlı kişilerle': 1,
         'eve getirilen ilacı': 1,
         'kbb uzmanı arkadaşım': 1,
         'doyma ve açlık duygularını': 1,
         'vücudumun her bir noktası': 1,
         'yatak döşek 15 gün': 1,
         'sürüntü alarak teşhisini koydukları': 1,
         'bir iki yorumum': 1,
         'başka bir belirtim': 1,
         'filyasyon ekibinin verdiği favicovir': 1,
         'bir saat süre': 1,
         'göğüs ve boğaz ağrısı': 1,
         'fit bir vucuda sahibim': 1,
         'bu is saka': 1,
         'doktorun soyledigi bu': 1,
         'yuzde 99 covid': 1,
         'artık test olmaya karar': 1,
         'aşırı anormal bir durumla': 1,
         '2.gün baş ağrısı devam': 1,
         'atılmayan bir balgam': 1,
         'dayanılmaz bir baş ağrısı': 1,
         'akraba ve internet tavsiyesiyle': 1,
         '2 gün daha izoleyim': 1,
         '%90 kayıp devam': 1,
         '%10 oranında': 1,
         'sert bir espresso': 1,
         'sırt ağrıları devam': 1,
         'herhangi bir aktiviteye': 1,
         'şiddetli bir semptom': 1,
         'göğüs ve bacak ağrıları': 1,
         'ilacın ilk dozunu': 1,
         'özel hastaneye gidip test': 1,
         'semptomları hissettiğim anda': 1,
         'bi de sözelciyim': 1,
         'öncelikle hafif atlatanlardanım': 1,
         ':burun tıkanıklığı': 1,
         'hafif vücut ağrısı': 1,
         'sadece kinovir adlı ilacı': 1,
         'okul öncesi öğretmeniyim': 1,
         'covid testini 05.04.21 tarihinde': 1,
         'her geçen gün': 1,
         'koku çok minimal seviyede': 1,
         'öyle bir ağırlık hissi': 1,
         'ekşi acı şekerli tatları': 1,
         'kan sulandırıcının üçüncüsünü': 1,
         'üç dört saat': 1,
         'şekerli, ekşi tatları': 1,
         'çok yan etkis': 1,
         'umarım bir sorun': 1,
         'ikamet ettiğim adrese': 1,
         'sistemdeki eski numaramdan': 1,
         'ayrı yaşadığım ailemden': 1,
         'çok büyük oranda': 1,
         'girmek zorunda olduğum eğitimlerim': 1,
         'belli bir oranda yerine': 1,
         'kolumu kaldıracak halim': 1,
         'hafif ateş yine devam': 1,
         'kalça ve bel ağrısı': 1,
         'inanılmaz bir halsizlik': 1,
         'rahatsız bir his': 1,
         'son iki gün karantina': 1,
         'hiç bir belirtiye': 1,
         'aynen öyle bir gün': 1,
         'standart sağlıklı bir gün': 1,
         'aynı şekilde karantinaya devam': 1,
         'artık yatmaktan sırtım': 1,
         'belirtisiz bir güne': 1,
         'olmak üzere ilaca devamke': 1,
         'favira isminde bir ilaç': 1,
         'iş yerindeki arkadaşlara': 1,
         'kendimi kötü hissetmişliğim': 1,
         'standart bir güne': 1,
         'tahminen 10 dk': 1,
         'akşam 17:30 sularında': 1,
         'kendime kızdığım nokta': 1,
         'çok düzenli bi şekilde': 1,
         'ama gerçekten baş ağrım': 1,
         'sırtımın belirli bölgelerinde': 1,
         'sürekli uyku isteği': 1,
         '1. gün= halsizlik': 1,
         'adam gibi kahvaltı': 1,
         'tedavi halen devam': 1,
         'ufak bir baskı': 1,
         'hafif bir ağrı': 1,
         'kafamın içindeki sümük': 1,
         'elimdeki ıhlamur dolu bardağı': 1,
         'beş kg sümük': 1,
         'kas ve eklem ağrısı': 1,
         'tat ve koku hissim': 1,
         '3.gün öksürüğüm devam': 1,
         'covid pozitif olma şüphem': 1,
         'arada kullandığım alerji ilacımı': 1,
         'hiç birinin davetine': 1,
         'covid olabilir ihtimali üzerine': 1,
         'bu durum beni tedirgin': 1,
         'yaklaşık 5 saat': 1,
         'yapılan covıd aşısı': 1,
         'başka bir varyant': 1,
         'sabahın 6 sında': 1,
         'bir de burnum': 1,
         'harici bir belirtim': 1,
         'bu yazıyı okuyanlara': 1,
         '12 kasım ek not': 1,
         'hafif balgamimsi bir şeyler': 1,
         'favimol adlı ilacı': 1,
         'çok hafif koku': 1,
         'daha 1.5 ay': 1,
         'iki biontech aşılıyım': 1,
         'burun açıcı sprey': 1,
         'hafif bir yorgunluk hissi': 1,
         'herhangi bi ilac': 1,
         'ayni seviyede belirtilerle devam': 1,
         'doktorun verdiği ilaclari': 1,
         'yoğun burun akıntısı': 1,
         'fena bi boğaz agrisiyla': 1,
         '37 derece ateşim': 1,
         'çayının tadını almadığımı fark': 1,
         'karin bölgesindeki ağrı': 1,
         '2 biontech aşım': 1,
         'maske takmayanın ebesini': 1,
         'maske aşı hikaye': 1,
         'sürekli grip olan ben': 1,
         'çok biraz öksürük': 1,
         'yorgunluk hissine devam': 1,
         'boğazımda hafif baskı devam': 1,
         'tat alma sorunum': 1,
         'geçmeyen bir ishal': 1,
         'ateş düşürücü ilaç': 1,
         ', yani bugün': 1,
         'başım fena haldeydi': 1,
         'ondan önceki gün': 1,
         'çok çok keskin kokuları': 1,
         'o doluluk hissi': 1,
         '10 şubat öksürük': 1,
         'içinde o enerjiden eser': 1,
         '8 şubat kırgınlık devam': 1,
         'süper bi kırgınlık': 1,
         'can sıkıcı ağrılarım': 1,
         '5 şubat gecesi': 1,
         'kan ve idrar tahlili': 1,
         '5 şubat bebeğimin ateşi': 1,
         'vücudumun saçma sapan yerlerinde': 1,
         '2 şubatta test': 1,
         'evdeki 8 aylık bebeğimi': 1,
         '29 - 30 ocak': 1,
         'bir kaç saate': 1,
         'bir kaç saat': 1,
         'takip eden gece': 1,
         'yaklaşık 1,5 ay': 1,
         '- altıncı gün': 1,
         '- dördüncü gün': 1,
         'iki katı etki': 1,
         '- ikinci gün': 1,
         '- birinci gün': 1,
         'sesim grip gibi sevgiler': 1,
         'sırt ağrısı 10 üzerinden': 1,
         'aslında 29. saatim': 1,
         'yiyip içmede sıkıntı': 1,
         'herhangi bir ilaç': 1,
         'filyasyon ekipleri tarafından': 1,
         'boğazda kaşınma hissi': 1,
         'boğazın her iki tarafında': 1,
         'boğazın sol tarafında': 1,
         'dolu olmayan öksürük': 1,
         'sürekli yatma ihtiyacı': 1,
         'boğaz yanması devam': 1,
         '3 biontech aşılıyım': 1,
         'daha önceki griplerimde': 1,
         'aile hekimimin önerdiği ilaçları': 1,
         'diğer ağrılarıma hiçbir faydası': 1,
         'yorgan döşek ağrı': 1,
         'hafif bir takılma hissiyle': 1,
         'korkunç bir karın ağrısı': 1,
         'yoğun baş ağrım': 1,
         'akşam terzi dönüşü': 1,
         'bugün yedinci gün': 1,
         'bugün birinci gün': 1,
         'kısa bir doktor muayenesine': 1,
         'illet bir şey': 1,
         '4. günün tekrarı niteliğinde': 1,
         'antibiyotiğin ikinci günü': 1,
         'bu sefer çok iğrenç': 1,
         'korkunç bir geniz akıntısı': 1,
         'acil doktoruna verdiği geralgine': 1,
         '14 günlük avelox antibiyotik': 1,
         '3. aşımın üzerinden': 1,
         '4. hatırlatma dozunu': 1,
         'not: 3 biontechliyim': 1,
         'ağrım aynı şekilde oradaydı': 1,
         'bir iki saat': 1,
         'boğaz ağrısı sebebiyle': 1,
         '- bütün bir gece': 1,
         'evde hızlı test': 1,
         'bir ton çay': 1,
         'artmaya çalışan ateş nedeniyle': 1})

for expr in counter:
    doc = nlp(expr)
    pos = [token.pos_ for token in doc]
    if pos[0] in ["ADV", "DET"]:
        print(pos, expr)


